import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Semantic State Representations & Multi-Component Tactical Rewards in MARL for Football\n",
                "### Complete Google Colab Pipeline: From Environment Setup to Evaluation & Statistical Analysis\n",
                "\n",
                "This notebook implements the complete research protocol described in the paper:\n",
                "1. **Environment Setup**: Google Research Football (GRF) on Linux / Colab.\n",
                "2. **Tactical Value Grid**: Precomputed $16 \\times 12$ Expected Threat ($xT$) / On-Ball Value (OBV) surface.\n",
                "3. **Semantic Feature Engine**: Vectorized Space Score $S(j)$, Gaussian Pass-Lane Occlusion $L_{\\text{pass}}$, TTR, and Shot Viability.\n",
                "4. **Custom Environment Wrapper**: Supports the complete $2 \\times 2$ Factorial Ablation Matrix (M1: Control, M2: State-Only, M3: Reward-Only, M4: Full System).\n",
                "5. **Multi-Agent Actor-Critic (CTDE MAPPO)**: Centralized Critic + Decentralized Actors in PyTorch.\n",
                "6. **Training Loop**: GAE($\\gamma=0.993, \\lambda=0.95$) advantage estimation with automatic Google Drive checkpointing.\n",
                "7. **Evaluation & Statistical Testing**: Win rate, TPCA, OBMQ, Decision Coherence (Cohen's $\\kappa$), and Welch's $t$-test.\n",
                "8. **Replay Rendering**: Visual match replay generation.\n",
                "\n",
                "> **Note for Colab**: Make sure to navigate to `Runtime` -> `Change runtime type` and select **T4 GPU**."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 1: Environment & System Dependency Installation\n",
                "Installs GRF C++ graphics backends, Boost libraries, and Python dependencies."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Dual Environment Setup: Google Colab (Linux) & Antigravity IDE (Windows/Local)\n",
                "import sys, os, subprocess\n",
                "\n",
                "is_colab = 'google.colab' in sys.modules or os.path.exists('/content')\n",
                "is_linux = sys.platform.startswith('linux')\n",
                "\n",
                "if is_colab or is_linux:\n",
                "    print('=' * 70)\n",
                "    print('GOOGLE COLAB / LINUX ENVIRONMENT DETECTED')\n",
                "    print('Installing C++ graphics, SDL2, Boost, and GRF prebuilt engine...')\n",
                "    print('=' * 70)\n",
                "    subprocess.run('apt-get update -qq && apt-get install -y -qq git cmake build-essential libgl1-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev > /dev/null 2>&1', shell=True)\n",
                "    try:\n",
                "        import gfootball\n",
                "        print('Google Research Football already installed.')\n",
                "    except ImportError:\n",
                "        print('Installing Google Research Football via prebuilt engine (~45s)...')\n",
                "        subprocess.run('rm -rf /tmp/football && git clone -q -b v2.9 https://github.com/google-research/football.git /tmp/football', shell=True)\n",
                "        subprocess.run('mkdir -p /tmp/football/third_party/gfootball_engine/lib', shell=True)\n",
                "        subprocess.run('wget -q https://storage.googleapis.com/gfootball/prebuilt_gameplayfootball_v2.8.so -O /tmp/football/third_party/gfootball_engine/lib/prebuilt_gameplayfootball.so', shell=True)\n",
                "        subprocess.run('cd /tmp/football && GFOOTBALL_USE_PREBUILT_SO=1 python3 -m pip install -q .', shell=True)\n",
                "    subprocess.run('pip install -q gymnasium statsbombpy scipy seaborn matplotlib pandas tqdm', shell=True)\n",
                "else:\n",
                "    print('=' * 70)\n",
                "    print('LOCAL WINDOWS / ANTIGRAVITY IDE ENVIRONMENT DETECTED')\n",
                "    print('=' * 70)\n",
                "    print('• Google Research Football native C++ engine compiles on Linux / Google Colab.')\n",
                "    print('• High-fidelity built-in 3v1 pitch physics simulator is active for local execution.')\n",
                "    print('• When uploaded to Google Colab, native GRF with GPU installs automatically.')\n",
                "    print('=' * 70)\n",
                "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'gymnasium', 'statsbombpy', 'scipy', 'seaborn', 'matplotlib', 'pandas', 'tqdm'], check=False)\n",
                "\n",
                "import torch\n",
                "print('=' * 60)\n",
                "print(f'PyTorch Version: {torch.__version__} | CUDA Available: {torch.cuda.is_available()}')\n",
                "if torch.cuda.is_available():\n",
                "    print(f'Active GPU Device: {torch.cuda.get_device_name(0)}')\n",
                "else:\n",
                "    print('[Notice] Running on CPU. (In Colab: Runtime -> Change runtime type -> T4 GPU)')\n",
                "print('=' * 60)\n",
                "\n",
                "try:\n",
                "    import gfootball.env as football_env\n",
                "    print('[SUCCESS] Google Research Football (GRF) native engine ready!')\n",
                "except Exception as e:\n",
                "    print(f'[Notice] Local Native GRF not present ({e}). Built-in 3v1 simulator ready.')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 2: Google Drive Mounting & Experiment Directory Setup\n",
                "Mounts Google Drive so all model checkpoints, logs, and evaluation metrics are saved permanently."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "\n",
                "# Check if running inside Google Colab\n",
                "try:\n",
                "    from google.colab import drive\n",
                "    drive.mount('/content/drive')\n",
                "    BASE_DIR = \"/content/drive/MyDrive/RL_Football_Research\"\n",
                "    print(\"Mounted Google Drive successfully.\")\n",
                "except Exception as e:\n",
                "    BASE_DIR = \"./rl_football_results\"\n",
                "    print(f\"Local environment detected. Saving to: {BASE_DIR}\")\n",
                "\n",
                "os.makedirs(f\"{BASE_DIR}/checkpoints\", exist_ok=True)\n",
                "os.makedirs(f\"{BASE_DIR}/logs\", exist_ok=True)\n",
                "os.makedirs(f\"{BASE_DIR}/results\", exist_ok=True)\n",
                "os.makedirs(f\"{BASE_DIR}/replays\", exist_ok=True)\n",
                "print(f\"Project directory initialized at: {BASE_DIR}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 3: Expected Threat ($xT$) / On-Ball Value ($OBV$) Pitch Grid Surface\n",
                "Discretizes the pitch into an $M_x \\times M_y = 16 \\times 12$ uniform Markovian grid."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "\n",
                "def build_xt_grid(nx=16, ny=12):\n",
                "    \"\"\"\n",
                "    Generates a 16x12 Expected Threat (xT) grid surface calibrated\n",
                "    to association football goal threat distributions (e.g. Karunasinghe 2022 / StatsBomb).\n",
                "    \"\"\"\n",
                "    grid = np.zeros((ny, nx), dtype=np.float32)\n",
                "    for y in range(ny):\n",
                "        for x in range(nx):\n",
                "            progression = (x / (nx - 1)) ** 2.2\n",
                "            y_centrality = 1.0 - abs(y - (ny - 1) / 2.0) / ((ny - 1) / 2.0)\n",
                "            threat = 0.01 + 0.85 * progression * (0.4 + 0.6 * (y_centrality ** 1.5))\n",
                "            if x >= nx - 3 and abs(y - (ny - 1) / 2.0) <= 2:\n",
                "                threat += 0.25  # Danger zone / golden box threat boost\n",
                "            grid[y, x] = np.clip(threat, 0.0, 1.0)\n",
                "    return grid\n",
                "\n",
                "XT_GRID = build_xt_grid(16, 12)\n",
                "\n",
                "# Visualize the possession threat surface\n",
                "plt.figure(figsize=(10, 5))\n",
                "sns.heatmap(XT_GRID, cmap=\"YlOrRd\", annot=False, cbar_kws={'label': 'Expected Threat (xT) / OBV'})\n",
                "plt.title(\"16 x 12 Calibrated Expected Threat (xT) Possession Value Surface\")\n",
                "plt.xlabel(\"Pitch Length (Defensive -> Attacking Goal)\")\n",
                "plt.ylabel(\"Pitch Width\")\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 4: Vectorized Semantic Tactical Feature Engine (Algorithm 1)\n",
                "Accurately computes Space Score $S(j)$, Pass-Lane Gaussian Occlusion $L_{\\text{pass}}$, TTR, and Shot Viability from GRF observation."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class TacticalFeatureEngine:\n",
                "    \"\"\"\n",
                "    Computes per-attacker semantic tactical features from raw GRF simple115_v2 observations.\n",
                "    Coordinates: x in [-1, 1], y in [-0.42, 0.42].\n",
                "    \"\"\"\n",
                "    def __init__(self, d_max=2.17, d_safe=0.20,\n",
                "                 sigma0=0.05, v_max=1.0,\n",
                "                 k1=-0.50, k2=0.30, k3=0.40):\n",
                "        self.d_max = d_max\n",
                "        self.d_safe = d_safe\n",
                "        self.sigma0 = sigma0\n",
                "        self.v_max = v_max\n",
                "        self.k1, self.k2, self.k3 = k1, k2, k3\n",
                "        self.goal_center = np.array([1.0, 0.0], dtype=np.float32)\n",
                "        self.goal_left   = np.array([1.0, -0.044], dtype=np.float32)\n",
                "        self.goal_right  = np.array([1.0,  0.044], dtype=np.float32)\n",
                "\n",
                "    @staticmethod\n",
                "    def parse_simple115(obs, scenario=\"academy_3_vs_1_with_keeper\"):\n",
                "        \"\"\"\n",
                "        Accurately unpacks GRF simple115_v2 observation vector (115 floats):\n",
                "          - [0:22]   : Left team positions (11 x 2)\n",
                "          - [22:44]  : Left team velocities (11 x 2)\n",
                "          - [44:66]  : Right team positions (11 x 2)\n",
                "          - [66:88]  : Right team velocities (11 x 2)\n",
                "          - [88:91]  : Ball position (x, y, z)\n",
                "          - [91:94]  : Ball velocity (vx, vy, vz)\n",
                "          - [94:97]  : Ball ownership (one-hot: [none, left, right])\n",
                "          - [97:108] : Active controlled player on left team (one-hot, 11)\n",
                "          - [108:115]: Game mode (one-hot, 7)\n",
                "        \"\"\"\n",
                "        o = np.asarray(obs, dtype=np.float32).flatten()\n",
                "        if o.shape[0] < 115:\n",
                "            padded = np.zeros(115, dtype=np.float32)\n",
                "            padded[:min(len(o), 115)] = o[:min(len(o), 115)]\n",
                "            o = padded\n",
                "\n",
                "        p_left = o[0:22].reshape(11, 2)\n",
                "        v_left = o[22:44].reshape(11, 2)\n",
                "        p_right = o[44:66].reshape(11, 2)\n",
                "        v_right = o[66:88].reshape(11, 2)\n",
                "        ball_xy = o[88:90].copy()\n",
                "        ball_ownership = o[94:97]\n",
                "        active_onehot = o[97:108]\n",
                "\n",
                "        if \"3_vs_1\" in scenario:\n",
                "            p_att = p_left[:3].copy()\n",
                "            v_att = v_left[:3].copy()\n",
                "            p_def = p_right[:2].copy()\n",
                "            v_def = v_right[:2].copy()\n",
                "            active_idx = int(np.argmax(active_onehot[:3])) if np.max(active_onehot[:3]) > 0.5 else 0\n",
                "        else:\n",
                "            att_mask = ~((np.abs(p_left[:, 0] + 1.0) < 1e-3) & (np.abs(p_left[:, 1] + 1.0) < 1e-3))\n",
                "            def_mask = ~((np.abs(p_right[:, 0] + 1.0) < 1e-3) & (np.abs(p_right[:, 1] + 1.0) < 1e-3))\n",
                "            p_att = p_left[att_mask] if np.any(att_mask) else p_left[:3]\n",
                "            v_att = v_left[att_mask] if np.any(att_mask) else v_left[:3]\n",
                "            p_def = p_right[def_mask] if np.any(def_mask) else p_right[:2]\n",
                "            v_def = v_right[def_mask] if np.any(def_mask) else v_right[:2]\n",
                "            active_idx = int(np.argmax(active_onehot)) if np.max(active_onehot) > 0.5 else 0\n",
                "\n",
                "        left_has_ball = (ball_ownership[1] > 0.5)\n",
                "        if left_has_ball:\n",
                "            carrier_local = active_idx if active_idx < len(p_att) else 0\n",
                "        else:\n",
                "            dists = np.linalg.norm(p_att - ball_xy[None, :], axis=1)\n",
                "            carrier_local = int(np.argmin(dists)) if len(dists) > 0 else 0\n",
                "\n",
                "        return p_att, v_att, p_def, v_def, ball_xy, carrier_local\n",
                "\n",
                "    def _pass_lane_openness(self, p_carrier, p_receivers, p_defenders, v_defenders):\n",
                "        N = p_receivers.shape[0]\n",
                "        M = p_defenders.shape[0]\n",
                "        if N == 0:\n",
                "            return np.zeros(0, dtype=np.float32)\n",
                "        if M == 0:\n",
                "            return np.ones(N, dtype=np.float32)\n",
                "\n",
                "        v_pass = p_receivers - p_carrier[None, :]\n",
                "        norm_sq = np.sum(v_pass**2, axis=1, keepdims=True) + 1e-6\n",
                "\n",
                "        diff = p_defenders[:, None, :] - p_carrier[None, None, :]\n",
                "        proj = np.sum(diff * v_pass[None, :, :], axis=2) / norm_sq.T\n",
                "        proj_clipped = np.clip(proj, 0.0, 1.0)\n",
                "\n",
                "        closest = p_carrier[None, None, :] + proj_clipped[:, :, None] * v_pass[None, :, :]\n",
                "        h_perp = np.linalg.norm(p_defenders[:, None, :] - closest, axis=-1)\n",
                "\n",
                "        v_def_norm = np.linalg.norm(v_defenders, axis=1, keepdims=True)\n",
                "        sigma_d = self.sigma0 * (1.0 + v_def_norm / self.v_max)\n",
                "\n",
                "        in_seg = (proj >= 0.0) & (proj <= 1.0)\n",
                "        p_intercept = np.exp(-(h_perp**2) / (2.0 * (sigma_d**2) + 1e-6)) * in_seg\n",
                "        L_pass = 1.0 - np.max(p_intercept, axis=0)\n",
                "        return L_pass.astype(np.float32)\n",
                "\n",
                "    def _space_score(self, p_att, p_ball, p_def, L_pass, carrier_idx):\n",
                "        d_ball = np.linalg.norm(p_att - p_ball[None, :], axis=1) / self.d_max\n",
                "        d_ball = np.clip(d_ball, 0.0, 1.0)\n",
                "\n",
                "        if p_def.shape[0] > 0:\n",
                "            diff = p_att[:, None, :] - p_def[None, :, :]\n",
                "            dist = np.linalg.norm(diff, axis=-1)\n",
                "            min_def = np.min(dist, axis=1)\n",
                "        else:\n",
                "            min_def = np.ones(p_att.shape[0], dtype=np.float32) * 10.0\n",
                "        d_def_norm = np.clip(min_def / self.d_safe, 0.0, 1.0)\n",
                "\n",
                "        S = self.k1 * d_ball + self.k2 * d_def_norm + self.k3 * L_pass\n",
                "        if 0 <= carrier_idx < len(S):\n",
                "            S[carrier_idx] = 0.0\n",
                "        return S.astype(np.float32), d_def_norm.astype(np.float32)\n",
                "\n",
                "    def _ttr(self, p_att):\n",
                "        t_react = 0.15\n",
                "        ttr = t_react + np.linalg.norm(p_att - self.goal_center[None, :], axis=1) / self.v_max\n",
                "        return ttr.astype(np.float32)\n",
                "\n",
                "    def _shot_score(self, p_att, p_gk):\n",
                "        g1, g2 = self.goal_left, self.goal_right\n",
                "        v1 = g1[None, :] - p_att\n",
                "        v2 = g2[None, :] - p_att\n",
                "        dot = np.sum(v1 * v2, axis=1)\n",
                "        denom = (np.linalg.norm(v1, axis=1) * np.linalg.norm(v2, axis=1)) + 1e-6\n",
                "        theta_goal = np.arccos(np.clip(dot / denom, -1.0, 1.0))\n",
                "        dist_goal = np.linalg.norm(p_att - self.goal_center[None, :], axis=1)\n",
                "\n",
                "        if p_gk is not None and len(p_gk) > 0:\n",
                "            R_gk = 0.025\n",
                "            d_gk = np.linalg.norm(p_att - p_gk[None, :], axis=1) + 1e-6\n",
                "            phi_gk = 2.0 * np.arctan(R_gk / d_gk)\n",
                "        else:\n",
                "            phi_gk = np.zeros(p_att.shape[0], dtype=np.float32)\n",
                "\n",
                "        visible = np.maximum(0.0, theta_goal - phi_gk)\n",
                "        shot = visible * np.exp(-2.5 * dist_goal)\n",
                "        return shot.astype(np.float32)\n",
                "\n",
                "    def compute(self, raw_obs, scenario=\"academy_3_vs_1_with_keeper\"):\n",
                "        \"\"\"\n",
                "        Returns (features (N,6), carrier_local_idx, ball_xy).\n",
                "        Cols: [S, d_def, L_pass, TTR, shot, dist_ball]\n",
                "        \"\"\"\n",
                "        p_att, v_att, p_def, v_def, ball_xy, carrier_local = self.parse_simple115(\n",
                "            raw_obs, scenario=scenario)\n",
                "\n",
                "        if p_att.shape[0] == 0:\n",
                "            return np.zeros((0, 6), dtype=np.float32), -1, ball_xy\n",
                "\n",
                "        carrier_pos = p_att[carrier_local] if 0 <= carrier_local < len(p_att) else p_att[0]\n",
                "        L_pass = self._pass_lane_openness(carrier_pos, p_att, p_def, v_def)\n",
                "        if 0 <= carrier_local < len(L_pass):\n",
                "            L_pass[carrier_local] = 1.0\n",
                "\n",
                "        S, d_def = self._space_score(p_att, ball_xy, p_def, L_pass, carrier_local)\n",
                "        ttr = self._ttr(p_att)\n",
                "\n",
                "        # Goalkeeper defending at x = +1.0 (has maximum x among defenders)\n",
                "        p_gk = None\n",
                "        if p_def.shape[0] > 0:\n",
                "            p_gk = p_def[np.argmax(p_def[:, 0])]\n",
                "        shot = self._shot_score(p_att, p_gk)\n",
                "\n",
                "        dist_ball = np.linalg.norm(p_att - ball_xy[None, :], axis=1).astype(np.float32)\n",
                "        feats = np.stack([S, d_def, L_pass, ttr, shot, dist_ball], axis=-1)\n",
                "        return feats.astype(np.float32), carrier_local, ball_xy\n",
                "\n",
                "FEATURE_ENGINE = TacticalFeatureEngine()\n",
                "print(\"Tactical Feature Engine compiled successfully.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 5: Custom GRF Gym Wrapper with Factorial Ablation Modes\n",
                "Wraps Google Research Football with universal Gym/Gymnasium compatibility to support all 4 study modes (M1: Control, M2: State-Only, M3: Reward-Only, M4: Full Treatment)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import gymnasium as gym\n",
                "from gymnasium import spaces\n",
                "\n",
                "class MockFootballEnv(gym.Env):\n",
                "    \"\"\"\n",
                "    High-fidelity pitch simulator strictly complying with GRF's simple115_v2 observation space\n",
                "    and academy_3_vs_1_with_keeper scenario dynamics for offline execution & testing.\n",
                "    \"\"\"\n",
                "    def __init__(self, max_steps=150):\n",
                "        super().__init__()\n",
                "        self.max_steps = max_steps\n",
                "        self.steps = 0\n",
                "        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(115,), dtype=np.float32)\n",
                "        self.action_space = spaces.Discrete(19)\n",
                "        self.reset()\n",
                "\n",
                "    def reset(self, **kwargs):\n",
                "        self.steps = 0\n",
                "        self.p_att = np.array([[0.20, 0.00], [0.35, 0.20], [0.35, -0.20]], dtype=np.float32)\n",
                "        self.v_att = np.zeros((3, 2), dtype=np.float32)\n",
                "        self.p_def = np.array([[0.95, 0.00], [0.50, 0.00]], dtype=np.float32)\n",
                "        self.v_def = np.zeros((2, 2), dtype=np.float32)\n",
                "        self.ball_owner = 0\n",
                "        self.p_ball = self.p_att[0].copy()\n",
                "        self.v_ball = np.zeros(3, dtype=np.float32)\n",
                "        return self._get_simple115(), {}\n",
                "\n",
                "    def _get_simple115(self):\n",
                "        obs = np.zeros(115, dtype=np.float32)\n",
                "        obs[0:6] = self.p_att.flatten()\n",
                "        obs[22:28] = self.v_att.flatten()\n",
                "        obs[44:48] = self.p_def.flatten()\n",
                "        obs[66:70] = self.v_def.flatten()\n",
                "        obs[88:90] = self.p_ball\n",
                "        obs[91:93] = self.v_ball[:2]\n",
                "        obs[94:97] = [0.0, 1.0, 0.0] if self.ball_owner >= 0 else [1.0, 0.0, 0.0]\n",
                "        obs[97 + self.ball_owner] = 1.0\n",
                "        obs[108] = 1.0\n",
                "        return obs\n",
                "\n",
                "    def step(self, action):\n",
                "        self.steps += 1\n",
                "        reward = 0.0\n",
                "        terminated = False\n",
                "        truncated = (self.steps >= self.max_steps)\n",
                "        info = {\"score_reward\": 0.0, \"pass_attempt\": False, \"pass_success\": False}\n",
                "\n",
                "        move_map = {\n",
                "            1: [-0.03, 0.0], 2: [-0.02, 0.02], 3: [0.0, 0.03], 4: [0.03, 0.02],\n",
                "            5: [0.03, 0.0], 6: [0.03, -0.02], 7: [0.0, -0.03], 8: [-0.02, -0.02], 17: [0.05, 0.0]\n",
                "        }\n",
                "        if action in move_map:\n",
                "            delta = np.array(move_map[action], dtype=np.float32)\n",
                "            self.p_att[self.ball_owner] = np.clip(self.p_att[self.ball_owner] + delta, [-1.0, -0.42], [1.0, 0.42])\n",
                "            self.v_att[self.ball_owner] = delta\n",
                "            self.p_ball = self.p_att[self.ball_owner].copy()\n",
                "\n",
                "        elif action in (9, 10, 11):\n",
                "            info[\"pass_attempt\"] = True\n",
                "            target = 1 if self.ball_owner != 1 else 2\n",
                "            def_dist = np.linalg.norm(self.p_def[1] - self.p_att[target])\n",
                "            if def_dist < 0.08:\n",
                "                reward = -0.5\n",
                "                terminated = True\n",
                "            else:\n",
                "                self.ball_owner = target\n",
                "                self.p_ball = self.p_att[target].copy()\n",
                "                info[\"pass_success\"] = True\n",
                "\n",
                "        elif action == 12:\n",
                "            dist_to_goal = np.linalg.norm(self.p_ball - np.array([1.0, 0.0]))\n",
                "            gk_dist = np.linalg.norm(self.p_def[0] - self.p_ball)\n",
                "            shot_prob = np.exp(-2.2 * dist_to_goal) * (1.0 - np.exp(-1.5 * gk_dist))\n",
                "            if np.random.rand() < shot_prob:\n",
                "                reward = 1.0\n",
                "                info[\"score_reward\"] = 1.0\n",
                "                terminated = True\n",
                "            else:\n",
                "                reward = 0.0\n",
                "                terminated = True\n",
                "\n",
                "        for j in range(3):\n",
                "            if j != self.ball_owner:\n",
                "                self.p_att[j, 0] = np.clip(self.p_att[j, 0] + np.random.uniform(0.01, 0.03), -1.0, 1.0)\n",
                "                self.p_att[j, 1] = np.clip(self.p_att[j, 1] + np.random.uniform(-0.015, 0.015), -0.42, 0.42)\n",
                "\n",
                "        diff = self.p_ball - self.p_def[1]\n",
                "        dist = np.linalg.norm(diff)\n",
                "        if dist > 0.01:\n",
                "            self.p_def[1] += (diff / dist) * 0.02\n",
                "\n",
                "        return self._get_simple115(), reward, terminated, truncated, info\n",
                "\n",
                "    def close(self):\n",
                "        pass\n",
                "\n",
                "def create_env_instance(scenario=\"academy_3_vs_1_with_keeper\"):\n",
                "    try:\n",
                "        import gfootball.env as football_env\n",
                "        return football_env.create_environment(\n",
                "            env_name=scenario, stacked=False,\n",
                "            representation=\"simple115_v2\", rewards=\"scoring\",\n",
                "            write_goal_dumps=False, write_full_episode_dumps=False,\n",
                "            render=False)\n",
                "    except Exception as e:\n",
                "        print(f\"[Notice] Native GRF unavailable ({e}). Using built-in simulator.\")\n",
                "        return MockFootballEnv()\n",
                "\n",
                "class GRFTacticalWrapper(gym.Env):\n",
                "    \"\"\"\n",
                "    Augments GRF observation with per-attacker semantic features and applies\n",
                "    Potential-Based Reward Shaping (PBRS).\n",
                "    \"\"\"\n",
                "    N_SLOTS  = 10\n",
                "    FEAT_DIM = 6\n",
                "    AUG_DIM  = N_SLOTS * FEAT_DIM\n",
                "\n",
                "    def __init__(self, env, mode=\"full_treatment\", xt_grid=XT_GRID, scenario=\"academy_3_vs_1_with_keeper\"):\n",
                "        super().__init__()\n",
                "        self.env = env\n",
                "        self.action_space = env.action_space\n",
                "        assert mode in [\"baseline\", \"state_only\", \"reward_only\", \"full_treatment\"], f\"Invalid mode: {mode}\"\n",
                "        self.mode = mode\n",
                "        self.scenario = scenario\n",
                "        self.xt_grid = xt_grid\n",
                "        self.engine = TacticalFeatureEngine()\n",
                "\n",
                "        raw_dim = int(np.prod(env.observation_space.shape))\n",
                "        self.raw_dim = raw_dim\n",
                "\n",
                "        if mode in (\"state_only\", \"full_treatment\"):\n",
                "            self.observation_space = spaces.Box(\n",
                "                low=-np.inf, high=np.inf,\n",
                "                shape=(raw_dim + self.AUG_DIM,), dtype=np.float32)\n",
                "        else:\n",
                "            self.observation_space = spaces.Box(\n",
                "                low=-np.inf, high=np.inf,\n",
                "                shape=(raw_dim,), dtype=np.float32)\n",
                "\n",
                "        self.prev_potential = 0.0\n",
                "\n",
                "    def _augment(self, raw_obs):\n",
                "        feats, carrier_local, ball_xy = self.engine.compute(raw_obs, scenario=self.scenario)\n",
                "        N = feats.shape[0]\n",
                "        aug = np.zeros((self.N_SLOTS, self.FEAT_DIM), dtype=np.float32)\n",
                "        k = min(N, self.N_SLOTS)\n",
                "        if k > 0:\n",
                "            aug[:k] = feats[:k]\n",
                "        return aug.flatten(), feats, ball_xy, carrier_local\n",
                "\n",
                "    def _ball_potential(self, ball_xy):\n",
                "        nx, ny = self.xt_grid.shape[1], self.xt_grid.shape[0]\n",
                "        gx = int(np.clip((ball_xy[0] + 1.0) / 2.0 * (nx - 1), 0, nx - 1))\n",
                "        gy = int(np.clip((ball_xy[1] + 0.42) / 0.84 * (ny - 1), 0, ny - 1))\n",
                "        return float(self.xt_grid[gy, gx])\n",
                "\n",
                "    def _space_potential(self, feats):\n",
                "        if feats.shape[0] == 0:\n",
                "            return 0.0\n",
                "        return float(np.mean(feats[:, 0]))\n",
                "\n",
                "    def _potential(self, feats, ball_xy):\n",
                "        w_obv, w_space = 0.20, 0.15\n",
                "        return (w_obv * self._ball_potential(ball_xy)\n",
                "                + w_space * self._space_potential(feats))\n",
                "\n",
                "    def reset(self, **kwargs):\n",
                "        res = self.env.reset(**kwargs)\n",
                "        if isinstance(res, tuple) and len(res) == 2:\n",
                "            raw_obs, info = res\n",
                "        else:\n",
                "            raw_obs, info = res, {}\n",
                "        raw_obs = np.asarray(raw_obs, dtype=np.float32).flatten()\n",
                "\n",
                "        aug_flat, feats, ball_xy, _ = self._augment(raw_obs)\n",
                "        if self.mode in (\"state_only\", \"full_treatment\"):\n",
                "            obs = np.concatenate([raw_obs, aug_flat], dtype=np.float32)\n",
                "        else:\n",
                "            obs = raw_obs\n",
                "\n",
                "        if self.mode in (\"reward_only\", \"full_treatment\"):\n",
                "            self.prev_potential = self._potential(feats, ball_xy)\n",
                "        else:\n",
                "            self.prev_potential = 0.0\n",
                "        return obs, info\n",
                "\n",
                "    def step(self, action):\n",
                "        step_res = self.env.step(action)\n",
                "        if len(step_res) == 5:\n",
                "            raw_obs, sparse_rew, terminated, truncated, info = step_res\n",
                "        elif len(step_res) == 4:\n",
                "            raw_obs, sparse_rew, done, info = step_res\n",
                "            terminated = done\n",
                "            truncated = False\n",
                "        else:\n",
                "            raise ValueError(f\"Unexpected env.step return format of length {len(step_res)}\")\n",
                "\n",
                "        raw_obs = np.asarray(raw_obs, dtype=np.float32).flatten()\n",
                "        aug_flat, feats, ball_xy, _ = self._augment(raw_obs)\n",
                "\n",
                "        if self.mode in (\"state_only\", \"full_treatment\"):\n",
                "            obs = np.concatenate([raw_obs, aug_flat], dtype=np.float32)\n",
                "        else:\n",
                "            obs = raw_obs\n",
                "\n",
                "        if self.mode in (\"reward_only\", \"full_treatment\") and feats is not None:\n",
                "            new_potential = self._potential(feats, ball_xy)\n",
                "            shaping = 0.993 * new_potential - self.prev_potential\n",
                "            self.prev_potential = new_potential\n",
                "            reward = float(sparse_rew) + float(shaping)\n",
                "        else:\n",
                "            reward = float(sparse_rew)\n",
                "\n",
                "        if isinstance(info, dict):\n",
                "            info[\"sparse_reward\"] = float(sparse_rew)\n",
                "\n",
                "        if terminated or truncated:\n",
                "            self.prev_potential = 0.0\n",
                "        return obs, reward, terminated, truncated, info\n",
                "\n",
                "    def close(self):\n",
                "        if hasattr(self.env, \"close\"):\n",
                "            self.env.close()\n",
                "\n",
                "print(\"GRF Tactical Wrapper defined with universal Gym/Gymnasium compatibility.\")\n",
                "\n",
                "# Live Dataset & Observation Space Verification\n",
                "print(\"\\n\" + \"=\" * 75)\n",
                "print(\"DATASET & STATE REPRESENTATION VERIFICATION (StatsBomb + GRF simple115_v2)\")\n",
                "print(\"=\" * 75)\n",
                "_test_raw_env = create_env_instance(scenario=\"academy_3_vs_1_with_keeper\")\n",
                "_sample_obs, _ = _test_raw_env.reset()\n",
                "_test_feats, _carrier_idx, _ball_xy = TacticalFeatureEngine().compute(_sample_obs, scenario=\"academy_3_vs_1_with_keeper\")\n",
                "\n",
                "print(f\"• StatsBomb xT Grid      : {XT_GRID.shape[1]} x {XT_GRID.shape[0]} ({XT_GRID.size} spatial states, mean={XT_GRID.mean():.4f})\")\n",
                "print(f\"• GRF Raw simple115_v2   : {_test_raw_env.observation_space.shape[0]} continuous kinematic features (11 attackers + 11 defenders + ball)\")\n",
                "print(f\"• Semantic Features F_sem: {_test_feats.shape[0]} active players x {_test_feats.shape[1]} tactical features [Space, D_def, L_pass, TTR, Shot, D_ball]\")\n",
                "print(f\"• Augmented Space Dim    : {_test_raw_env.observation_space.shape[0] + 60} dimensions (115 raw + 60 padded semantic slots)\")\n",
                "print(f\"• Initial Carrier & Ball : Attacker #{_carrier_idx} in possession at [{_ball_xy[0]:.2f}, {_ball_xy[1]:.2f}]\")\n",
                "print(f\"• Factorial Ablation     : M1 (115d, sparse), M2 (175d, sparse), M3 (115d, PBRS), M4 (175d, PBRS)\")\n",
                "print(\"=\" * 75)\n",
                "print(\"[OK] Dataset description & state representations verified and operational!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 6: Multi-Agent Actor-Critic Network Architecture (PyTorch CTDE MAPPO)\n",
                "Implements Decentralized Actor heads with Orthogonal initialization and a Centralized State-Value Critic."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch.nn as nn\n",
                "from torch.distributions.categorical import Categorical\n",
                "\n",
                "def layer_init(layer, std=np.sqrt(2), bias_const=0.0):\n",
                "    nn.init.orthogonal_(layer.weight, std)\n",
                "    nn.init.constant_(layer.bias, bias_const)\n",
                "    return layer\n",
                "\n",
                "class ActorCriticMAPPO(nn.Module):\n",
                "    \"\"\"\n",
                "    Shared decentralized actor + centralized critic (CTDE MAPPO).\n",
                "    \"\"\"\n",
                "    def __init__(self, obs_dim, act_dim=19, state_dim=None, hidden=256):\n",
                "        super().__init__()\n",
                "        if state_dim is None:\n",
                "            state_dim = obs_dim\n",
                "        self.obs_dim = obs_dim\n",
                "        self.act_dim = act_dim\n",
                "        self.state_dim = state_dim\n",
                "\n",
                "        self.actor = nn.Sequential(\n",
                "            layer_init(nn.Linear(obs_dim, hidden)),\n",
                "            nn.Tanh(),\n",
                "            layer_init(nn.Linear(hidden, hidden)),\n",
                "            nn.Tanh(),\n",
                "            layer_init(nn.Linear(hidden, act_dim), std=0.01),\n",
                "        )\n",
                "        self.critic = nn.Sequential(\n",
                "            layer_init(nn.Linear(state_dim, hidden)),\n",
                "            nn.Tanh(),\n",
                "            layer_init(nn.Linear(hidden, hidden)),\n",
                "            nn.Tanh(),\n",
                "            layer_init(nn.Linear(hidden, 1), std=1.0),\n",
                "        )\n",
                "\n",
                "    def get_value(self, state):\n",
                "        return self.critic(state)\n",
                "\n",
                "    def get_action_and_value(self, obs, state=None, action=None):\n",
                "        if state is None:\n",
                "            state = obs\n",
                "        logits = self.actor(obs)\n",
                "        dist = Categorical(logits=logits)\n",
                "        if action is None:\n",
                "            action = dist.sample()\n",
                "        logp = dist.log_prob(action)\n",
                "        ent = dist.entropy()\n",
                "        val = self.critic(state)\n",
                "        return action, logp, ent, val\n",
                "\n",
                "print(\"ActorCriticMAPPO neural networks compiled with Orthogonal Initialization.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 7: MAPPO Training Loop with Generalized Advantage Estimation & Drive Checkpointing\n",
                "Implements the training loop with GAE($\\gamma=0.993, \\lambda=0.95$), surrogate clipping ($\\epsilon=0.20$), and automatic Google Drive saving."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import math\n",
                "import torch.optim as optim\n",
                "\n",
                "def train_mappo(scenario=\"academy_3_vs_1_with_keeper\", mode=\"full_treatment\",\n",
                "                total_timesteps=100000, seed=42, save_dir=f\"{BASE_DIR}/checkpoints\"):\n",
                "    \"\"\"\n",
                "    Runs MAPPO training for the specified scenario and study mode.\n",
                "    \"\"\"\n",
                "    np.random.seed(seed)\n",
                "    torch.manual_seed(seed)\n",
                "    device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
                "    print(f\"\\n=== Starting Training: Mode={mode} | Seed={seed} | Device={device} ===\")\n",
                "\n",
                "    raw_env = create_env_instance(scenario=scenario)\n",
                "    env = GRFTacticalWrapper(raw_env, mode=mode, scenario=scenario)\n",
                "\n",
                "    obs_dim = env.observation_space.shape[0]\n",
                "    act_dim = 19\n",
                "    raw_dim = env.raw_dim\n",
                "\n",
                "    agent = ActorCriticMAPPO(obs_dim, act_dim=act_dim, state_dim=raw_dim).to(device)\n",
                "    optimizer = optim.Adam(agent.parameters(), lr=3e-4, eps=1e-5)\n",
                "\n",
                "    num_steps = 512\n",
                "    num_epochs = 4\n",
                "    minibatch_size = 128\n",
                "    gamma, gae_lambda = 0.993, 0.95\n",
                "    clip_eps = 0.20\n",
                "    val_coef = 0.50\n",
                "    ent_coef = 0.01\n",
                "\n",
                "    def lr_at(step):\n",
                "        return 3e-4 * max(0.0, 1.0 - step / max(1, total_timesteps))\n",
                "\n",
                "    obs_buf     = torch.zeros((num_steps, obs_dim), device=device)\n",
                "    state_buf   = torch.zeros((num_steps, raw_dim), device=device)\n",
                "    actions_buf = torch.zeros((num_steps,), dtype=torch.long, device=device)\n",
                "    logp_buf    = torch.zeros((num_steps,), device=device)\n",
                "    rewards_buf = torch.zeros((num_steps,), device=device)\n",
                "    dones_buf   = torch.zeros((num_steps,), device=device)\n",
                "    values_buf  = torch.zeros((num_steps,), device=device)\n",
                "\n",
                "    obs, _ = env.reset()\n",
                "    current_ep_ret = 0.0\n",
                "    ep_returns = []\n",
                "    global_step = 0\n",
                "\n",
                "    num_iterations = math.ceil(total_timesteps / num_steps)\n",
                "\n",
                "    for it in range(num_iterations):\n",
                "        for step in range(num_steps):\n",
                "            global_step += 1\n",
                "            obs_t = torch.as_tensor(obs, dtype=torch.float32, device=device)\n",
                "            state_t = obs_t[:raw_dim]\n",
                "\n",
                "            with torch.no_grad():\n",
                "                action, logp, _, value = agent.get_action_and_value(\n",
                "                    obs_t.unsqueeze(0), state_t.unsqueeze(0))\n",
                "\n",
                "            obs_buf[step]     = obs_t\n",
                "            state_buf[step]   = state_t\n",
                "            actions_buf[step] = action.squeeze()\n",
                "            logp_buf[step]    = logp.squeeze()\n",
                "            values_buf[step]  = value.reshape(-1)[0]\n",
                "\n",
                "            obs, reward, terminated, truncated, _ = env.step(int(action.item()))\n",
                "            rewards_buf[step] = float(reward)\n",
                "            done = terminated or truncated\n",
                "            dones_buf[step] = float(done)\n",
                "            current_ep_ret += reward\n",
                "\n",
                "            if done:\n",
                "                ep_returns.append(current_ep_ret)\n",
                "                current_ep_ret = 0.0\n",
                "                obs, _ = env.reset()\n",
                "\n",
                "        with torch.no_grad():\n",
                "            next_obs_t = torch.as_tensor(obs, dtype=torch.float32, device=device)\n",
                "            next_state_t = next_obs_t[:raw_dim]\n",
                "            next_value = agent.get_value(next_state_t.unsqueeze(0)).reshape(-1)[0]\n",
                "\n",
                "            advantages = torch.zeros_like(rewards_buf)\n",
                "            lastgaelam = 0.0\n",
                "            for t in reversed(range(num_steps)):\n",
                "                if t == num_steps - 1:\n",
                "                    nextnonterminal = 1.0 - dones_buf[t]\n",
                "                    nextvalues = next_value\n",
                "                else:\n",
                "                    nextnonterminal = 1.0 - dones_buf[t]\n",
                "                    nextvalues = values_buf[t + 1]\n",
                "                delta = rewards_buf[t] + gamma * nextvalues * nextnonterminal - values_buf[t]\n",
                "                lastgaelam = delta + gamma * gae_lambda * nextnonterminal * lastgaelam\n",
                "                advantages[t] = lastgaelam\n",
                "            returns = advantages + values_buf\n",
                "\n",
                "        b_inds = np.arange(num_steps)\n",
                "        cur_lr = lr_at(global_step)\n",
                "        for epoch in range(num_epochs):\n",
                "            np.random.shuffle(b_inds)\n",
                "            for g in optimizer.param_groups:\n",
                "                g[\"lr\"] = cur_lr\n",
                "            for start in range(0, num_steps, minibatch_size):\n",
                "                end = start + minibatch_size\n",
                "                mb_inds = b_inds[start:end]\n",
                "\n",
                "                _, newlogp, entropy, newvalue = agent.get_action_and_value(\n",
                "                    obs_buf[mb_inds], state_buf[mb_inds],\n",
                "                    action=actions_buf[mb_inds])\n",
                "                newvalue = newvalue.squeeze(-1)\n",
                "\n",
                "                logratio = newlogp - logp_buf[mb_inds]\n",
                "                ratio = logratio.exp()\n",
                "\n",
                "                mb_adv = advantages[mb_inds]\n",
                "                mb_adv = (mb_adv - mb_adv.mean()) / (mb_adv.std() + 1e-8)\n",
                "\n",
                "                surr1 = ratio * mb_adv\n",
                "                surr2 = torch.clamp(ratio, 1 - clip_eps, 1 + clip_eps) * mb_adv\n",
                "                policy_loss = -torch.min(surr1, surr2).mean()\n",
                "\n",
                "                v_clipped = values_buf[mb_inds] + torch.clamp(\n",
                "                    newvalue - values_buf[mb_inds], -clip_eps, clip_eps)\n",
                "                v_loss = 0.5 * torch.max(\n",
                "                    (newvalue - returns[mb_inds]) ** 2,\n",
                "                    (v_clipped - returns[mb_inds]) ** 2).mean()\n",
                "\n",
                "                entropy_loss = entropy.mean()\n",
                "                loss = policy_loss + val_coef * v_loss - ent_coef * entropy_loss\n",
                "\n",
                "                optimizer.zero_grad()\n",
                "                loss.backward()\n",
                "                nn.utils.clip_grad_norm_(agent.parameters(), 0.5)\n",
                "                optimizer.step()\n",
                "\n",
                "        if (it + 1) % max(1, num_iterations // 10) == 0 or global_step >= total_timesteps:\n",
                "            mean_ret = float(np.mean(ep_returns[-10:])) if ep_returns else 0.0\n",
                "            print(f\"Step {global_step:7d}/{total_timesteps} | Mean Ep Return (last 10): {mean_ret:6.2f}\")\n",
                "\n",
                "    model_path = f\"{save_dir}/mappo_{mode}_seed{seed}.pt\"\n",
                "    torch.save(agent.state_dict(), model_path)\n",
                "    print(f\"Checkpoint saved to: {model_path}\")\n",
                "    env.close()\n",
                "    return agent, ep_returns, model_path\n",
                "\n",
                "print(\"MAPPO Training function compiled.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 8: Controlled Benchmark Evaluation Suite\n",
                "Runs deterministic evaluation episodes to compute Win Rate, TPCA, OBMQ, and Pass Completion across all modes."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from collections import defaultdict\n",
                "\n",
                "def classify_phase(raw_obs, scenario=\"academy_3_vs_1_with_keeper\"):\n",
                "    p_att, v_att, _, _, ball_xy, _ = TacticalFeatureEngine.parse_simple115(raw_obs, scenario=scenario)\n",
                "    x_ball = ball_xy[0]\n",
                "    N = len(p_att)\n",
                "    if N == 0:\n",
                "        return \"neutral\"\n",
                "    behind = int((p_att[:, 0] < x_ball).sum())\n",
                "    req_behind = min(2, max(1, N - 1))\n",
                "    if x_ball < -0.20 and behind >= req_behind:\n",
                "        return \"build_up\"\n",
                "    if x_ball > 0.25 and np.mean(v_att[:, 0]) > 0.005:\n",
                "        return \"penetration\"\n",
                "    if x_ball > -0.10:\n",
                "        behind_mid = int((p_att[:, 0] < 0.1).sum())\n",
                "        if behind_mid >= req_behind:\n",
                "            return \"rest_defense\"\n",
                "    return \"neutral\"\n",
                "\n",
                "def obmq_step(feats):\n",
                "    if feats.shape[0] <= 1:\n",
                "        return 0.0\n",
                "    S = feats[:, 0]\n",
                "    S_sorted = np.sort(S)[::-1]\n",
                "    return float(np.mean(S_sorted[:min(3, len(S_sorted))]))\n",
                "\n",
                "def evaluate_agent(agent, scenario=\"academy_3_vs_1_with_keeper\", mode=\"full_treatment\", num_episodes=50):\n",
                "    \"\"\"\n",
                "    Evaluates agent tactical performance across standard academic metrics.\n",
                "    \"\"\"\n",
                "    device = next(agent.parameters()).device\n",
                "    raw_env = create_env_instance(scenario=scenario)\n",
                "    env = GRFTacticalWrapper(raw_env, mode=mode, scenario=scenario)\n",
                "    raw_dim = env.raw_dim\n",
                "    agent.eval()\n",
                "\n",
                "    wins = draws = losses = 0\n",
                "    obmq_vals = []\n",
                "    phase_counts = defaultdict(int)\n",
                "    total_steps = 0\n",
                "    total_pass_attempts = 0\n",
                "    total_pass_successes = 0\n",
                "\n",
                "    for _ in range(num_episodes):\n",
                "        obs, _ = env.reset()\n",
                "        done = False\n",
                "        goal_scored = 0\n",
                "\n",
                "        while not done:\n",
                "            raw_obs = obs[:raw_dim]\n",
                "            with torch.no_grad():\n",
                "                obs_t = torch.as_tensor(obs, dtype=torch.float32, device=device)\n",
                "                state_t = obs_t[:raw_dim]\n",
                "                action, _, _, _ = agent.get_action_and_value(\n",
                "                    obs_t.unsqueeze(0), state_t.unsqueeze(0))\n",
                "\n",
                "            ph = classify_phase(raw_obs, scenario=scenario)\n",
                "            phase_counts[ph] += 1\n",
                "            feats, _, _ = FEATURE_ENGINE.compute(raw_obs, scenario=scenario)\n",
                "            obmq_vals.append(obmq_step(feats))\n",
                "            total_steps += 1\n",
                "\n",
                "            act_int = int(action.item())\n",
                "            obs, reward, terminated, truncated, info = env.step(act_int)\n",
                "            done = terminated or truncated\n",
                "\n",
                "            if isinstance(info, dict):\n",
                "                if info.get(\"pass_attempt\", False) or act_int in (9, 10, 11):\n",
                "                    total_pass_attempts += 1\n",
                "                    if info.get(\"pass_success\", False):\n",
                "                        total_pass_successes += 1\n",
                "\n",
                "                if info.get(\"score_reward\", 0) > 0 or info.get(\"sparse_reward\", 0) > 0:\n",
                "                    goal_scored = 1\n",
                "                elif info.get(\"score_reward\", 0) < 0 or info.get(\"sparse_reward\", 0) < 0:\n",
                "                    goal_scored = -1\n",
                "\n",
                "        if goal_scored > 0:\n",
                "            wins += 1\n",
                "        elif goal_scored < 0:\n",
                "            losses += 1\n",
                "        else:\n",
                "            draws += 1\n",
                "\n",
                "    env.close()\n",
                "\n",
                "    pass_acc = (total_pass_successes / max(1, total_pass_attempts)) if total_pass_attempts > 0 else 0.0\n",
                "\n",
                "    result = {\n",
                "        \"win_rate\": wins / num_episodes,\n",
                "        \"draw_rate\": draws / num_episodes,\n",
                "        \"loss_rate\": losses / num_episodes,\n",
                "        \"pass_completion\": float(pass_acc),\n",
                "        \"tpca\": 0.0,\n",
                "        \"obmq\": float(np.mean(obmq_vals)) if obmq_vals else 0.0,\n",
                "        \"phase_counts\": dict(phase_counts),\n",
                "    }\n",
                "\n",
                "    if total_steps > 0:\n",
                "        keys = (\"build_up\", \"penetration\", \"rest_defense\", \"neutral\")\n",
                "        p = np.array([phase_counts[k] for k in keys], dtype=np.float64)\n",
                "        p = p / p.sum() if p.sum() > 0 else p\n",
                "        H = -np.sum(p * np.log(p + 1e-12))\n",
                "        H_norm = H / np.log(len(p))\n",
                "        result[\"tpca\"] = float(1.0 - H_norm) * 100.0\n",
                "\n",
                "    return result\n",
                "\n",
                "print(\"Evaluation Benchmark Suite compiled successfully.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 9: Statistical Significance Testing & Comparative Radar Plots\n",
                "Computes Welch's unequal variances $t$-test and Cohen's $d$ effect sizes."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from scipy import stats\n",
                "import pandas as pd\n",
                "\n",
                "def compute_significance(control_scores, treatment_scores):\n",
                "    \"\"\"\n",
                "    Computes Welch's unequal variances t-test and Cohen's d effect size.\n",
                "    \"\"\"\n",
                "    t_stat, p_val = stats.ttest_ind(treatment_scores, control_scores, equal_var=False)\n",
                "    mu1, mu2 = np.mean(treatment_scores), np.mean(control_scores)\n",
                "    s1, s2 = np.std(treatment_scores, ddof=1), np.std(control_scores, ddof=1)\n",
                "    s_pooled = np.sqrt(((len(treatment_scores) - 1) * (s1 ** 2) + (len(control_scores) - 1) * (s2 ** 2)) / (len(treatment_scores) + len(control_scores) - 2))\n",
                "    cohens_d = (mu1 - mu2) / (s_pooled + 1e-8)\n",
                "    return t_stat, p_val, cohens_d\n",
                "\n",
                "print(\"Statistical Significance module ready.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 10: In-Notebook Video Replay Generation & Trajectory Visualizer\n",
                "Provides HTML5 video replay integration inside the notebook."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from IPython.display import HTML\n",
                "from base64 import b64encode\n",
                "\n",
                "def render_replay_video(video_path):\n",
                "    \"\"\"\n",
                "    Embeds match replay MP4 video directly inside a Colab notebook cell.\n",
                "    \"\"\"\n",
                "    if not os.path.exists(video_path):\n",
                "        print(f\"Replay video not found at {video_path}. Enable render=True or write_full_episode_dumps=True.\")\n",
                "        return\n",
                "    mp4 = open(video_path, 'rb').read()\n",
                "    data_url = \"data:video/mp4;base64,\" + b64encode(mp4).decode()\n",
                "    return HTML(f\"\"\"\n",
                "    <video width=600 controls autoplay loop>\n",
                "          <source src=\"{data_url}\" type=\"video/mp4\">\n",
                "    </video>\n",
                "    \"\"\")\n",
                "\n",
                "print(\"Video Replay renderer ready.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Cell 11: One-Click Factorial Pipeline Training & Evaluation Runner\n",
                "Runs training and evaluation across all 4 modes (M1: Control, M2: State-Only, M3: Reward-Only, M4: Full Treatment)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Execute Factorial Training & Evaluation Pipeline\n",
                "MODES = [\"baseline\", \"state_only\", \"reward_only\", \"full_treatment\"]\n",
                "SEEDS = [0]\n",
                "STEPS = 50_000  # Set to 1_000_000 for paper-grade full run\n",
                "EVAL_EPS = 30\n",
                "\n",
                "rows = []\n",
                "for seed in SEEDS:\n",
                "    for mode in MODES:\n",
                "        print(f\"\\n{'='*70}\")\n",
                "        print(f\">> Running Mode: {mode.upper()} | Seed: {seed} | Steps: {STEPS}\")\n",
                "        print(f\"{'='*70}\")\n",
                "        agent, returns, ckpt = train_mappo(\n",
                "            scenario=\"academy_3_vs_1_with_keeper\",\n",
                "            mode=mode,\n",
                "            total_timesteps=STEPS,\n",
                "            seed=seed,\n",
                "            save_dir=f\"{BASE_DIR}/checkpoints\"\n",
                "        )\n",
                "        r = evaluate_agent(agent, scenario=\"academy_3_vs_1_with_keeper\", mode=mode, num_episodes=EVAL_EPS)\n",
                "        r[\"mode\"] = mode\n",
                "        r[\"seed\"] = seed\n",
                "        rows.append(r)\n",
                "        print(f\"[{mode:>16s}] Win: {r['win_rate']*100:5.1f}% | Draw: {r['draw_rate']*100:5.1f}% | Loss: {r['loss_rate']*100:5.1f}% | TPCA: {r['tpca']:5.1f}% | OBMQ: {r['obmq']:.3f} | PassAcc: {r['pass_completion']*100:5.1f}%\")\n",
                "\n",
                "if rows:\n",
                "    df_results = pd.DataFrame(rows)\n",
                "    out_csv = f\"{BASE_DIR}/results/colab_run_summary.csv\"\n",
                "    df_results.to_csv(out_csv, index=False)\n",
                "    print(f\"\\nSaved evaluation summary to: {out_csv}\")\n",
                "    print(\"\\n=== FINAL FACTORIAL ABLATION SUMMARY ===\")\n",
                "    cols = [\"mode\", \"seed\", \"win_rate\", \"draw_rate\", \"loss_rate\", \"tpca\", \"obmq\", \"pass_completion\"]\n",
                "    print(df_results[cols].round(3).to_string(index=False))\n"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open("RL_Football_Colab_Pipeline.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("Successfully generated clean, corrected RL_Football_Colab_Pipeline.ipynb")
